[opener]
edit = [
	{ run = 'nvim "$@"', block = true },
]
play = [
	{ run = 'vlc "$@"', orphan = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
sound = [
	{ run = 'audacity "$@"', orphan=true, desc = "Open" },
]


[open]
prepend_rules = [
	{ name = "*.mp3", use = "sound" },
	{ name = "*.mp4a", use = "sound" },
]
